### ISSUE TITLE
discord lags

### ISSUE THREAD

**Issue by DragonFIghter603** [DragonFIghter603/aeonetica#33]

**Comment by Spydr06** [comment]
nice

**Comment by Spydr06** [comment]
![image](https://github.com/DragonFIghter603/aeonetica/assets/58859306/9f3de288-fd29-488c-aa70-80f94da8cdce)

**Comment by DragonFIghter603** [comment]
okay so your latency is totally acceptable in the game, but for me it was terrible yesterday

**Comment by DragonFIghter603** [comment]
> ![image](https://user-images.githubusercontent.com/58859306/243181338-9f3de288-fd29-488c-aa70-80f94da8cdce.png)

so much fun

**Comment by Spydr06** [comment]
totally

**Comment by Spydr06** [comment]
we _could_ switch to matrix/irc

**Comment by DragonFIghter603** [comment]
sure, i made amatrix acc: dragon_pi

**Comment by Spydr06** [comment]
have to make one too xD

**Comment by Spydr06** [comment]
(never used irc for anything xD)

**Comment by DragonFIghter603** [comment]
whats your matrix handle?

**Comment by DragonFIghter603** [comment]
![image](https://github.com/DragonFIghter603/aeonetica/assets/75088766/70696329-cef1-4b61-ac6d-4d142e6451f7)

**Comment by Spydr06** [comment]
![image](https://github.com/DragonFIghter603/aeonetica/assets/58859306/247a3313-cec4-4bac-9233-b1ace53d9c8c)

**Comment by DragonFIghter603** [comment]
![image](https://github.com/DragonFIghter603/aeonetica/assets/75088766/a12ee46a-a5e5-4008-9512-fd013a7030c7)
2.7k ms, pretty accurate by just judging the delay

**Comment by Spydr06** [comment]
![image](https://github.com/DragonFIghter603/aeonetica/assets/58859306/7808e491-b1d0-4747-b44e-4700a19e5a67)
going up again, I have a matrix acc now too

**Comment by DragonFIghter603** [comment]
aaaand worse again, whats your matrix handle now?

**Comment by Spydr06** [comment]
imma close this since matrix is working
